vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: /uploads/teachers
            upload_destination: '%kernel.project_dir%/public/uploads/teachers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        student_image:
            uri_prefix: /assets/images/student
            upload_destination: '%kernel.project_dir%/public/assets/images/student'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 
