vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: /uploads/trachers/
            upload_destination: '%kernel.project_dir%/public/uploads/teachers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 
