vich_uploader:
    db_driver: orm
    mappings:
        student_image:
                uri_prefix: '%student_profile_path%'
                upload_destination: '%kernel.project_dir%/public%student_profile_path%'
                namer: 
                    service: Vich\UploaderBundle\Naming\PropertyNamer
                    options: { property: 'matricule' } 
                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true 