version: '3.8'
services:
  php:
    restart: unless-stopped
    image: lucasluk798/php:8.2
    volumes:
      - .:/var/www:delegate
    environment:
      APP_ENV: dev
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bethesda
      MYSQL_USER: arsene
      MYSQL_PASSWORD: pws_arsene
    volumes:
      - ./var:/var/www/var
      - ./tools/docker/mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha