<?php

namespace AppBundle\Repository;
use AppBundle\Entity\SchoolYear;
/**
 * AttibutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttibutionRepository extends \Doctrine\ORM\EntityRepository {

    public function findNotAttributedCoursesThisYear(SchoolYear $year) {
        $query = $this->getEntityManager()
                ->createQuery(
                        "SELECT crse
                             FROM  AppBundle:Course  crse
                             JOIN AppBundle:Attribution att WITH  att.course  =  crse.id
                             JOIN AppBundle:SchoolYear schoolYear  WITH  att.schoolYear     =  schoolYear.id
                             WHERE att.schoolYear = :year
                             AND crse.attributed =:attributed 
                            "
                )->setParameter('year', $year)
                ->setParameter('attributed', false)
         ;

        return $query->getResult();
    }

    public function findAllThisYear(SchoolYear $year) {
      
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.schoolYear', 'sc')
            ->leftJoin('a.teacher', 't')
                ->where('sc.id=:year')
                ->orderBy('t.username')
                ->setParameter('year', $year->getId());
              
        return $qb->getQuery()->getResult();
    }

}
